### ISSUE TITLE
Switch to main branch before update

### ISSUE THREAD

**Issue by uyha** [NvChad/extensions#26]
**Is your feature request related to a problem? Please describe.**
Currently, I have `NvChad` set up as a submodule of my config repo, this means everytime I clone my config repo with submodules, `NvChad` is detached from the `main` branch. This leads to updating using `<leader>uu` failing since it's trying to pull from a detached head.

**Describe the solution you'd like**
Switch to `main` branch before pulling.

**Describe alternatives you've considered**
Not changing anything at all since this a minor quality of life improvement for a niche setup.

**Comment by LeonHeidelbach** [comment]
@uyha this sounds like a very specific issue related to your setup. Generally speaking I would recommend you to use a git bare repo for your dotfiles and to only commit the custom folder to it so that you won't have to register NvChad as a submodule. @siduck if you think this is necessary I could implement this, and always make sure to switch to the default `main` branch or the optional remote branch key set in the user's `chadrc`.

**Comment by siduck** [comment]
@LeonHeidelbach does adding this feature mean that nvchad git repo could be used in another git repos?

**Comment by uyha** [comment]
@LeonHeidelbach yes, i'm aware that this is very niche so it makes sense if you don't want to implement this.

**Comment by LeonHeidelbach** [comment]
> @LeonHeidelbach does adding this feature mean that nvchad git repo could be used in another git repos? If yes then add this feature, I was tired with adding a separate custom dir* in my dotfiles repo, it'd be great to add the whole nvim folder itself!

@siduck it already can be registered as a submodule in other repos. Just updating the submodules will as @uyha said, bring about some issues. This change would just make sure that the updater only pulls changes from the branch that users specifically define in their `chadrc` or by default the `main` branch. This means that if you for example manually checked out the dev branch of NvChad and ran `:NvChadUpdate` from there, the updater would checkout the tracked branch defined in your `chadrc` or the default `main` branch first, before doing anything.

**Comment by uyha** [comment]
that is more troublesome than what i need to do already, I think it's not necessary

**Comment by siduck** [comment]
@LeonHeidelbach add this feature then

**Comment by LeonHeidelbach** [comment]
@uyha I mean this could be a neat features in some use cases but maybe annoying in others. I think it could be nice to have and since @siduck is all for it I will look into adding it later today.

**Comment by LeonHeidelbach** [comment]
@siduck @uyha Done! Try it out and let me know if everything works as expected (which it should, I tested it :wink:) https://github.com/NvChad/extensions/pull/27

**Comment by uyha** [comment]
I'm not sure how to try this, could you tell me how?

**Comment by LeonHeidelbach** [comment]
@uyha since @siduck has already merged it just open nvim and run `:PackerSync`, restart your nvim and the commit should be applied. Then do what you do when updating your submodules and check if the NvChad repo is on a detached commit (or simply checkout another branch yourself for testing purposes). Open nvim and press `<leader>uu` or run `:NvChadUpdate`. After the updater is done you should now be on the defined update_branch which is `main` by default.

**Comment by uyha** [comment]
yes, that works nicely
