### ISSUE TITLE
cheatsheet attempt to index local 'key' (a boolean value)

### ISSUE THREAD

**Issue by wasden** [NvChad/extensions#7]
This PR intruduced a new bug
https://github.com/NvChad/NvChad/pull/737

**Comment by siduck** [comment]
i didnt face it

**Comment by wasden** [comment]
cheatsheet.lua:79,  type(key) maybe false or nil

**Comment by siduck** [comment]
cheatsheet works fine here :/ . do you get that error while opening cheatsheet

**Comment by zahimeen** [comment]
I actually get the same issue
https://github.com/NvChad/NvChad/issues/860

**Comment by zahimeen** [comment]
@siduck
@wasden 

The issue only occurs when one of the keymappings is set to false. I had created this issue yesterday and I was gonna fix it it today, but realised that cheatsheet was located here, so should I close that issue?

https://github.com/NvChad/NvChad/issues/860

**Comment by zahimeen** [comment]
## Bug
In the mappings cheatsheet, using the boolean `false` to disable a mapping, causes an error to crash the cheatsheet.

## To Reproduce
1. Use the `false` or `true` keyword as the setting for any of the regular or plugin mappings.
2. Try to open the mappings cheatsheet.

## Expected Behaviour
When using the `false` keyword for any of the regular or plugin mappings, the cheatsheet should open without error. The mapping should either not be displayed in the cheatsheet at all or should be represented without a keymap.

## Screenshots
![image](https://user-images.githubusercontent.com/76834998/156776308-662f740a-a8b3-4d60-9e80-b83821702f1b.png)

## Techinical Information
 - Manjaro Linux x86_64
 - alacritty 0.10.1 (2844606d)
 - NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
Features: +acl +iconv +tui
